source 'http://rubygems.org'

gem 'github-pages'
gem 'rake'
gem 'pygments.rb', '~> 1.2.1'
gem 'jekyll'
gem 'html-proofer', '~> 3.7.0'
gem 'jemoji'
gem 'jekyll-mentions'
gem 'jekyll-seo-tag'
gem 'jekyll-feed'
gem 'jekyll-sitemap'
gem 'jekyll-gist'
